[phases.setup]
run = "pip install -r requirements.txt"

[phases.build]
run = "python manage.py collectstatic --noinput"

[phases.start]
run = "gunicorn plagrasim_detector.wsgi:application --bind 0.0.0.0:8000"
